
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  


variables:
  BACKEND_NAV: backend
  FRONT_NAV: front-end

default:
  image: node:16.10.0


  

.package_install:
  script: &installing_dependencies
    - npm install
    

.navigation:
  script:
    - cd 

.job1: 
  stage: build  
  tags:
    - ci
  script:
    - echo $CI_JOB_IMAGE	
    - node --version

install_job_back_end:
  stage: build  
  tags: 
    - ci
  script:
    - cd $BACKEND_NAV
    - *installing_dependencies    
    - echo successfully updated
    - ls
  artifacts:
    paths:
      - backend/node_modules
    expire_in: 1 week

install_job_front_end:
  stage: build 
  tags:
    - ci    
  script:
    - cd $FRONT_NAV
    - *installing_dependencies
    - echo front-end install
  artifacts:
    paths:
      - front-end/node_modules      
    expire_in: 1 week
    when: always

eslint_back_end:
  stage: test
  tags:
    - ci
  dependencies:
    - install_job_back_end
  script:
    - cd $BACKEND_NAV
    - npm run eslint
  needs: [install_job_back_end]
     

eslint_front_end:
  stage: test
  tags: 
    - ci
  dependencies:
    - install_job_front_end
  script:
    - cd $FRONT_NAV
    - npm run eslint
  needs: ['install_job_front_end']

unittesting 1/2:
  stage: test
  tags:
    - ci
  script:
    - cd $FRONT_NAV 
    - npm run test
  dependencies:
    - install_job_front_end
  needs:
    - install_job_front_end


unittesting 2/2:
  stage: test
  tags:
    - ci
  dependencies:
    - install_job_back_end
  needs:
    - install_job_back_end
  script:
    - cd $BACKEND_NAV 
    - npm run test
  allow_failure: true

  

integratingtest:
  image: cypress/browsers:node16.5.0-chrome94-ff93
  stage: test  
  tags: 
    - ci 
  dependencies:
    - install_job_back_end
    - install_job_front_end
  needs:
    - install_job_back_end
    - install_job_front_end
  script:
    - cd $FRONT_NAV
    - npm ci
    - npm start &
    - sleep 10
    - cd ../$BACKEND_NAV
    - npm start &
    - sleep 10
    - cd ../$FRONT_NAV
    - npx cypress run --record --key $CYPRESS_CI_RECORDING_STRING --parallel --browser chrome --group 'UI - Chrome'
  
deploy:
  stage: deploy
  before_script:
  - apt-get update -qq && apt-get install -y curl
  - curl -L https://fly.io/install.sh | sh
  - export FLYCTL_INSTALL="/root/.fly"
  - export PATH="$FLYCTL_INSTALL/bin:$PATH"  
  tags:
    - ci
  script: 
    - echo $FLY_USER_TOKEN
    - /root/.fly/bin/flyctl auth login --email $FLY_USER_EMAIL --password $FLY_USER_PASSWORD 
    - /root/.fly/bin/flyctl secrets set PORT=$PORT MONGODB_PASSWORD=$MONGODB_PASSWORD MONGODB_USER=$MONGODB_USER MONGODB_URL=$MONGODB_URL SECRET_KEY=$SECRET_KEY
    - /root/.fly/bin/flyctl deploy


