name: My Gallery deploy

on: 
  push: 
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_testing_pipeline:
    runs-on: ubuntu-latest
    steps: 
       - name: action check
         run: echo 'This is working '